name: daffy

ghc-options: -freverse-errors -Wall

default-extensions:
  - BangPatterns
  - DeriveGeneric
  - DuplicateRecordFields
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - aeson
    - async
    - attoparsec
    - base
    - bytestring
    - containers
    - managed
    - process >= 1.5 && < 1.6
    - safe-exceptions
    - stm
    - streaming
    - temporary
    - text
    - transformers

executables:
  daffy:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - aeson
      - base
      - daffy
      - http-types
      - text
      - wai
      - warp
      - websockets

        #  daffy-socket-server:
        #    source-dirs: app
        #    main: SocketServer.hs
        #    other-modules: []
        #    ghc-options: -threaded
        #    dependencies:
        #      - base
        #      - bytestring
        #      - containers
        #      - daffy
        #      - directory
        #      - managed
        #      - mtl
        #      - network
        #      - safe-exceptions
        #      - streaming
        #      - text
        #
        #  daffy-console-client:
        #    source-dirs: app
        #    main: ConsoleClient.hs
        #    other-modules: []
        #    dependencies:
        #      - base
        #      - bytestring
        #      - managed
        #      - network

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - daffy
      - hspec
      - text
