name: daffy

ghc-options: -freverse-errors -Wall

default-extensions:
  - BangPatterns
  - DeriveGeneric
  - DuplicateRecordFields
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - aeson
    - async
    - attoparsec
    - base
    - bytestring
    - managed
    - process >= 1.5 && < 1.6
    - safe-exceptions
    - stm
    - streaming
    - temporary
    - text
    - transformers

executables:
  daffy:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - aeson
      - base
      - daffy
      - http-types
      - text
      - wai
      - warp

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - daffy
      - hspec
      - text
