name: daffy

ghc-options: -freverse-errors -Wall

default-extensions:
  - BangPatterns
  - DeriveGeneric
  - DuplicateRecordFields
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - aeson
    - attoparsec
    - base
    - bytestring
    - process
    - temporary
    - text

executables:
  daffy:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - aeson
      - base
      - daffy
      - http-types
      - text
      - unordered-containers
      - wai
      - warp

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - bytestring
      - daffy
      - hspec
